language: pyhton
python:
  - "2.7"
  - "3.4"
  - "3.6"
  - 3.7

#command to install dependencies
install:
  - pip3 install Flask

# command to run tests
script:
  - sh run_travis.sh

# command to set up services
services: postgresql

# command to set up environmental variables
env: 
  - BLOG_DATABASE=sqlite:///db.db